### ISSUE TITLE
クライアントが最後に送ったwsメッセージが数秒遅れて配信される。

### ISSUE THREAD

**Issue by tkimuranet** [OpenAyame/ayame#7]
クライアントが最後に送ったメッセージは、最大で数秒遅れて、pingメッセージの配信タイミングでもう一方のクライアントに配信される気がします。
signaling_handler.goの
w.Write(message)
の後に、
w.Close()
を追加したら即時に配信されるようになりました。

**Comment by kdxu** [comment]
報告ありがとうございます！確認&修正次第返信いたします。

**Comment by kdxu** [comment]
https://github.com/OpenAyame/ayame/commit/eef287f3c22cd8219aa06323782e63b507d46c04
にて
```go
w.Close()
```
を追加して動作検証しました。

**Comment by kdxu** [comment]
また、表題の問題に関して、上記の修正を加えることで ws のメッセージが即時配信されることが確認できました。
